<template>
  <section class="mx-auto max-w-7xl lg:px-8">
    <h1 class="mb-7 text-5xl">Privacy Policy</h1>

    <div class="container mb-5">

      <p><strong>1. Introduction</strong></p>
      <p>1.1 We are committed to safeguarding the privacy of our website visitors, service users, individual customers and customer personnel.</p>
      <p>1.2 This policy applies where we are acting as a data controller with respect to the personal data of such persons; in other words, where we determine the purposes and means of the processing of that personal data.</p>
      <p>1.3 Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to receive direct marketing communications. You can access the privacy controls via <em>https://cloud.billabear.com</em>.</p>
      <p>1.4 We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and services, we will ask you to consent to our use of cookies when you first visit our website.</p>
      <p>1.5 In this policy, "we", "us" and "our" refer to <em>Humbly Arrogant Software Ltd</em>.</p>
      <p><br /> </p>
      <p><strong>2. The personal data that we collect</strong></p>
      <p>2.1 In this Section 2 we have set out the general categories of personal data that we proces and, in the case of personal data that we did not obtain directly from you, information about the source and specific categories of that data.</p>
      <p>2.2 We may process data enabling us to get in touch with you ("<strong>contact data</strong>"). The contact data may include your name, email address, telephone number, postal address and/or social media account identifiers. The source of the contact data is you and/or your employer. If you log into our website using a social media account, we will obtain elements of the contact data from the relevant social media account provider.</p>
      <p>2.3 We may process your website user account data ("<strong>account data</strong>"). The account data may include your account identifier, name, email address, business name, account creation and modification dates, website settings and marketing preferences. The primary source of the account data is you and/or your employer, although some elements of the account data may be generated by our website. If you log into our website using a social media account, we will obtain elements of the account data from the relevant social media account provider.</p>
      <p>2.4 We may process information relating to transactions, including purchases of goods and/or services, that you enter into with us and/or through our website ("<strong>transaction data</strong>"). The transaction data may include your name, your contact details, your payment card details (or other payment details) and the transaction details. The source of the transaction data is you and/or our payment services provider.</p>
      <p>2.5 We may process information contained in or relating to any communication that you send to us or that we send to you ("<strong>communication data</strong>"). The communication data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms.</p>
      <p>2.6 We may process data about your use of our website and services ("<strong>usage data</strong>"). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking system.</p>
      <p><br /> </p>
      <p class=""><strong>3. Purposes of processing and legal bases</strong></p>
      <p>3.1 In this Section 3, we have set out the purposes for which we may process personal data and the legal bases of the processing.</p>
      <p>3.2 <strong>Operations </strong>- We may process your personal data for the purposes of operating our website, the processing and fulfilment of orders, providing our services, supplying our goods, generating invoices, bills and other payment-related documentation, and credit control. The legal basis for this processing is our legitimate interests, namely the proper administration of our website, services and business OR the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract.</p>
      <p>3.3 <strong>Relationships and communications</strong> - We may process contact data, account data, transaction data and/or communication data for the purposes of managing our relationships, communicating with you (excluding communicating for the purposes of direct marketing) by email, SMS, post, fax and/or telephone, providing support services and complaint handling. The legal basis for this processing is our legitimate interests, namely communications with our website visitors, service users, individual customers and customer personnel, the maintenance of relationships, and the proper administration of our website, services and business.</p>
      <p>3.4 <strong>Direct marketing </strong>- We may process contact data, account data and/or transaction data for the purposes of creating, targeting and sending direct marketing communications by email, SMS, post and/or fax and making contact by telephone for marketing-related purposes. The legal basis for this processing is consent.</p>
      <p>3.5 <strong>Research and analysis </strong>- We may process usage data and/or transaction data for the purposes of researching and analysing the use of our website and services, as well as researching and analysing other interactions with our business. The legal basis for this processing is our legitimate interests, namely monitoring, supporting, improving and securing our website, services and business generally.</p>
      <p>3.6 <strong>Record keeping </strong>- We may process your personal data for the purposes of creating and maintaining our databases, back-up copies of our databases and our business records generally The legal basis for this processing is our legitimate interests, namely ensuring that we have access to all the information we need to properly and efficiently run our business in accordance with this policy.</p>
      <p>3.7 <strong>Security </strong>- We may process your personal data for the purposes of security and the prevention of fraud and other criminal activity. The legal basis of this processing is our legitimate interests, namely the protection of our website, services and business, and the protection of others.</p>
      <p>3.8 <strong>Legal claims</strong> - We may process your personal data where necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is our legitimate interests, namely the protection and assertion of our legal rights, your legal rights and the legal rights of others.</p>
      <p>3.9 <strong>Legal compliance and vital interests</strong> - We may also process your personal data where such processing is necessary for compliance with a legal obligation to which we are subject or in order to protect your vital interests or the vital interests of another natural person.</p>
      <p><br /> </p>
      <p><strong>4. Providing your personal data to others</strong></p>
      <p>4.1 We may disclose your personal data to our insurers and/or professional advisers insofar as reasonably necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice.</p>
      <p>4.2 Your personal data held in our website database will be stored on the servers of our hosting services providers.</p>
      <p>4.3 We may disclose personal data to our suppliers or subcontractorsinsofar as reasonably necessary for operation of the business.</p>
      <p>4.4 Financial transactions relating to our website and services are handled by our payment services providers, <em>Stripe</em>. We will share transaction data with our payment services providers only to the extent necessary for the purposes of processing your payments, refunding such payments and dealing with complaints and queries relating to such payments and refunds. You can find information about the payment services providers' privacy policies and practices at <em>https://stripe.com/de/privacy</em>.</p>
      <p>4.5 In addition to the specific disclosures of personal data set out in this Section 4, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise, or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.</p>
      <p><br /> </p>
      <p><strong>6. Retaining and deleting personal data</strong></p>
      <p>6.1 This Section 6 sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.</p>
      <p>6.2 Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</p>
      <p>6.3 Notwithstanding the other provisions of this Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</p>
      <p><br /> </p>
      <p><strong>7. Your rights</strong></p>
      <p>7.1 In this Section 7, we have listed the rights that you have under data protection law.</p>
      <p>7.2 Your principal rights under data protection law are:</p>
      <p>(a) <strong>the right to access</strong> - you can ask for copies of your personal data;</p>
      <p>(b) <strong>the right to rectification</strong> - you can ask us to rectify inaccurate personal data and to complete incomplete personal data;</p>
      <p>(c) <strong>the right to erasure</strong> - you can ask us to erase your personal data;</p>
      <p>(d) <strong>the right to restrict processing</strong> - you can ask us to restrict the processing of your personal data;</p>
      <p>(e) <strong>the right to object to processing</strong> - you can object to the processing of your personal data;</p>
      <p>(f) <strong>the right to data portability</strong> - you can ask that we transfer your personal data to another organisation or to you;</p>
      <p>(g) <strong>the right to complain to a supervisory authority</strong> - you can complain about our processing of your personal data; and</p>
      <p>(h) <strong>the right to withdraw consent</strong> - to the extent that the legal basis of our processing of your personal data is consent, you can withdraw that consent.</p>
      <p>7.3 These rights are subject to certain limitations and exceptions. You can learn more about the rights of data subjects by visiting <span style="color: #000080;"><span lang="zxx"><u><a href="https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/"><span style="color: #0000ff;">https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/</span></a></u></span></span>.</p>
      <p>7.4 You may exercise any of your rights in relation to your personal data by written notice to us, using the contact details set out below.</p>
      <p><br /> </p>
      <p><strong>8. About cookies</strong></p>
      <p>8.1 A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.</p>
      <p>8.2 Cookies may be either "persistent" cookies or "session" cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.</p>
      <p>8.3 Cookies may not contain any information that personally identifies a user, but personal data that we store about you may be linked to the information stored in and obtained from cookies.</p>
      <p><br /> </p>
      <p><strong>9. Cookies that we use</strong></p>
      <p>9.1 We use cookies for the following purposes:</p>
      <p>(a) <strong>authentication and status</strong> - we use cookies to identify you when you visit our website and as you navigate our website, and to help us determine if you are logged into our website (cookies used for this purpose are: <em>identify cookies</em><em>)</em></p>
      <p><br /> </p>
      <p><strong>10. Cookies used by our service providers</strong></p>
      <p>10.1 Our service providers use cookies and those cookies may be stored on your computer when you visit our website.</p>
      <p><br /> </p>
      <p><strong>11. Managing cookies</strong></p>
      <p>11.1 Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:</p>
      <p>(a) <span style="color: #000080;"><span lang="zxx"><u><a href="https://support.google.com/chrome/answer/95647"><span style="color: #0000ff;">https://support.google.com/chrome/answer/95647</span></a></u></span></span> (Chrome);</p>
      <p>(b) <span style="color: #000080;"><span lang="zxx"><u><a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences"><span style="color: #0000ff;">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</span></a></u></span></span> (Firefox);</p>
      <p>(c) <span style="color: #000080;"><span lang="zxx"><u><a href="https://help.opera.com/en/latest/security-and-privacy/"><span style="color: #0000ff;">https://help.opera.com/en/latest/security-and-privacy/</span></a></u></span></span> (Opera);</p>
      <p>(d) <span style="color: #000080;"><span lang="zxx"><u><a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies"><span style="color: #0000ff;">https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</span></a></u></span></span> (Internet Explorer);</p>
      <p>(e) <span style="color: #000080;"><span lang="zxx"><u><a href="https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac"><span style="color: #0000ff;">https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac</span></a></u></span></span> (Safari); and</p>
      <p>(f) <span style="color: #000080;"><span lang="zxx"><u><a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy"><span style="color: #0000ff;">https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy</span></a></u></span></span> (Edge).</p>
      <p>11.2 Blocking all cookies will have a negative impact upon the usability of many websites.</p>
      <p>11.3 If you block cookies, you will not be able to use all the features on our website.</p>
      <p><br /> </p>
      <p><strong>12. Amendments</strong></p>
      <p>12.1 We may update this policy from time to time by publishing a new version on our website.</p>
      <p>12.2 You should check this page occasionally to ensure you are happy with any changes to this policy.</p>
      <p>12.3 We will notify you of significant changes to this policy by email.</p>
      <p><br /> </p>
      <p><strong>13. Our details</strong></p>
      <p>13.1 This website is owned and operated by <em>Humbly Arrogant Software Limited</em>.</p>
      <p>13.2 We are registered in England under registration number 14903642, and our registered office is at 71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ.</p>
      <p>13.3 Our principal place of business is at 71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ.</p>
      <p>13.4 You can contact us:</p>
      <p>(a) by post, to the postal address given above;</p>
      <p>(b) by email, using the email address published on our website.</p>
    </div>
  </section>
</template>

<script lang="ts">
import {defineComponent} from 'vue'

export default defineComponent({
  name: "privacy-policy"
})
</script>

<style scoped>

</style>
